CREATE TABLE drone
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    serial_number VARCHAR(100) NOT NULL,
    model ENUM('LIGHT_WEIGHT', 'MIDDLE_WEIGHT', 'CRUISER_WEIGHT', 'HEAVY_WEIGHT') NOT NULL,
    weight_limit INT CHECK(weight_limit BETWEEN 0 AND 500) NOT NULL,
    battery NUMERIC(4, 1) NOT NULL,
    state ENUM('IDLE', 'LOADING', 'LOADED', 'DELIVERING', 'DELIVERED', 'RETURNING') NOT NULL,
    UNIQUE (serial_number)
);

CREATE TABLE medicine
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR NOT NULL,
    weight FLOAT NOT NULL,
    code VARCHAR NOT NULL,
    image BLOB NOT NULL,
    UNIQUE (name, code)
);

CREATE TABLE cargo
(
    drone_id BIGINT,
    medicine_id BIGINT,
    PRIMARY KEY (drone_id, medicine_id),
    FOREIGN KEY (drone_id) REFERENCES drone(id),
    FOREIGN KEY (medicine_id) REFERENCES medicine(id)
);